// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgres

import (
	"database/sql"
	"time"
)

type Person struct {
	ID               int64        `db:"id" json:"id"`
	TelegramID       int64        `db:"telegram_id" json:"telegram_id"`
	FirstName        string       `db:"first_name" json:"first_name"`
	LastName         string       `db:"last_name" json:"last_name"`
	Language         string       `db:"language" json:"language"`
	TelegramLanguage string       `db:"telegram_language" json:"telegram_language"`
	MainPasswordHash string       `db:"main_password_hash" json:"main_password_hash"`
	FakePasswordHash string       `db:"fake_password_hash" json:"fake_password_hash"`
	LocationLat      int64        `db:"location_lat" json:"location_lat"`
	LocationLon      int64        `db:"location_lon" json:"location_lon"`
	IsAdmin          sql.NullBool `db:"is_admin" json:"is_admin"`
	CreatedAt        time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time    `db:"updated_at" json:"updated_at"`
}
