// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgres

import (
	"context"
)

type Querier interface {
	CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error)
	GetNearValidators(ctx context.Context, arg GetNearValidatorsParams) ([]int64, error)
	GetPersonByTelegramID(ctx context.Context, telegramID int64) (Person, error)
	SetAdmin(ctx context.Context, telegramID int64) error
}

var _ Querier = (*Queries)(nil)
