// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: proto/AuthSrv.proto

package AuthSrv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckPersonExistByTelegramIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TelegramID int64 `protobuf:"varint,1,opt,name=telegramID,proto3" json:"telegramID,omitempty"`
}

func (x *CheckPersonExistByTelegramIDRequest) Reset() {
	*x = CheckPersonExistByTelegramIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_AuthSrv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckPersonExistByTelegramIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPersonExistByTelegramIDRequest) ProtoMessage() {}

func (x *CheckPersonExistByTelegramIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AuthSrv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPersonExistByTelegramIDRequest.ProtoReflect.Descriptor instead.
func (*CheckPersonExistByTelegramIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_AuthSrv_proto_rawDescGZIP(), []int{0}
}

func (x *CheckPersonExistByTelegramIDRequest) GetTelegramID() int64 {
	if x != nil {
		return x.TelegramID
	}
	return 0
}

type CheckPersonExistByTelegramIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CheckPersonExistByTelegramIDResponse) Reset() {
	*x = CheckPersonExistByTelegramIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_AuthSrv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckPersonExistByTelegramIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPersonExistByTelegramIDResponse) ProtoMessage() {}

func (x *CheckPersonExistByTelegramIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AuthSrv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPersonExistByTelegramIDResponse.ProtoReflect.Descriptor instead.
func (*CheckPersonExistByTelegramIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_AuthSrv_proto_rawDescGZIP(), []int{1}
}

func (x *CheckPersonExistByTelegramIDResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

// ---------------------------------------
type Person struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TelegramID       int64   `protobuf:"varint,2,opt,name=telegramID,proto3" json:"telegramID,omitempty"`
	FirstName        string  `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName         string  `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Language         string  `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	TelegramLanguage string  `protobuf:"bytes,6,opt,name=telegramLanguage,proto3" json:"telegramLanguage,omitempty"`
	MainPasswordHash string  `protobuf:"bytes,7,opt,name=mainPasswordHash,proto3" json:"mainPasswordHash,omitempty"`
	FakePasswordHash string  `protobuf:"bytes,8,opt,name=fakePasswordHash,proto3" json:"fakePasswordHash,omitempty"`
	LocationLat      float64 `protobuf:"fixed64,9,opt,name=locationLat,proto3" json:"locationLat,omitempty"`
	LocationLon      float64 `protobuf:"fixed64,10,opt,name=locationLon,proto3" json:"locationLon,omitempty"`
}

func (x *Person) Reset() {
	*x = Person{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_AuthSrv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AuthSrv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_proto_AuthSrv_proto_rawDescGZIP(), []int{2}
}

func (x *Person) GetTelegramID() int64 {
	if x != nil {
		return x.TelegramID
	}
	return 0
}

func (x *Person) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Person) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Person) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Person) GetTelegramLanguage() string {
	if x != nil {
		return x.TelegramLanguage
	}
	return ""
}

func (x *Person) GetMainPasswordHash() string {
	if x != nil {
		return x.MainPasswordHash
	}
	return ""
}

func (x *Person) GetFakePasswordHash() string {
	if x != nil {
		return x.FakePasswordHash
	}
	return ""
}

func (x *Person) GetLocationLat() float64 {
	if x != nil {
		return x.LocationLat
	}
	return 0
}

func (x *Person) GetLocationLon() float64 {
	if x != nil {
		return x.LocationLon
	}
	return 0
}

type CreatePersonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Person *Person `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
}

func (x *CreatePersonRequest) Reset() {
	*x = CreatePersonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_AuthSrv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersonRequest) ProtoMessage() {}

func (x *CreatePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AuthSrv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersonRequest.ProtoReflect.Descriptor instead.
func (*CreatePersonRequest) Descriptor() ([]byte, []int) {
	return file_proto_AuthSrv_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePersonRequest) GetPerson() *Person {
	if x != nil {
		return x.Person
	}
	return nil
}

type CreatePersonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CreatePersonResponse) Reset() {
	*x = CreatePersonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_AuthSrv_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersonResponse) ProtoMessage() {}

func (x *CreatePersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AuthSrv_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersonResponse.ProtoReflect.Descriptor instead.
func (*CreatePersonResponse) Descriptor() ([]byte, []int) {
	return file_proto_AuthSrv_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePersonResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetPersonByTelegramIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TelegramID   int64  `protobuf:"varint,1,opt,name=telegramID,proto3" json:"telegramID,omitempty"`
	PasswordHash string `protobuf:"bytes,2,opt,name=PasswordHash,proto3" json:"PasswordHash,omitempty"`
}

func (x *GetPersonByTelegramIDRequest) Reset() {
	*x = GetPersonByTelegramIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_AuthSrv_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPersonByTelegramIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonByTelegramIDRequest) ProtoMessage() {}

func (x *GetPersonByTelegramIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AuthSrv_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonByTelegramIDRequest.ProtoReflect.Descriptor instead.
func (*GetPersonByTelegramIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_AuthSrv_proto_rawDescGZIP(), []int{5}
}

func (x *GetPersonByTelegramIDRequest) GetTelegramID() int64 {
	if x != nil {
		return x.TelegramID
	}
	return 0
}

func (x *GetPersonByTelegramIDRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type GetPersonByTelegramIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Person *Person `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
}

func (x *GetPersonByTelegramIDResponse) Reset() {
	*x = GetPersonByTelegramIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_AuthSrv_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPersonByTelegramIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonByTelegramIDResponse) ProtoMessage() {}

func (x *GetPersonByTelegramIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AuthSrv_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonByTelegramIDResponse.ProtoReflect.Descriptor instead.
func (*GetPersonByTelegramIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_AuthSrv_proto_rawDescGZIP(), []int{6}
}

func (x *GetPersonByTelegramIDResponse) GetPerson() *Person {
	if x != nil {
		return x.Person
	}
	return nil
}

type GetNearValidatorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationLat float64 `protobuf:"fixed64,1,opt,name=locationLat,proto3" json:"locationLat,omitempty"`
	LocationLon float64 `protobuf:"fixed64,2,opt,name=locationLon,proto3" json:"locationLon,omitempty"`
	Distance    int64   `protobuf:"varint,3,opt,name=distance,proto3" json:"distance,omitempty"`
	Limit       int32   `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset      int32   `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetNearValidatorsRequest) Reset() {
	*x = GetNearValidatorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_AuthSrv_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNearValidatorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearValidatorsRequest) ProtoMessage() {}

func (x *GetNearValidatorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AuthSrv_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearValidatorsRequest.ProtoReflect.Descriptor instead.
func (*GetNearValidatorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_AuthSrv_proto_rawDescGZIP(), []int{7}
}

func (x *GetNearValidatorsRequest) GetLocationLat() float64 {
	if x != nil {
		return x.LocationLat
	}
	return 0
}

func (x *GetNearValidatorsRequest) GetLocationLon() float64 {
	if x != nil {
		return x.LocationLon
	}
	return 0
}

func (x *GetNearValidatorsRequest) GetDistance() int64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *GetNearValidatorsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetNearValidatorsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetNearValidatorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Validators []int64 `protobuf:"varint,1,rep,packed,name=validators,proto3" json:"validators,omitempty"`
}

func (x *GetNearValidatorsResponse) Reset() {
	*x = GetNearValidatorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_AuthSrv_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNearValidatorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearValidatorsResponse) ProtoMessage() {}

func (x *GetNearValidatorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AuthSrv_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearValidatorsResponse.ProtoReflect.Descriptor instead.
func (*GetNearValidatorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_AuthSrv_proto_rawDescGZIP(), []int{8}
}

func (x *GetNearValidatorsResponse) GetValidators() []int64 {
	if x != nil {
		return x.Validators
	}
	return nil
}

type SetAdminRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TelegramID int64 `protobuf:"varint,1,opt,name=telegramID,proto3" json:"telegramID,omitempty"`
}

func (x *SetAdminRequest) Reset() {
	*x = SetAdminRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_AuthSrv_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAdminRequest) ProtoMessage() {}

func (x *SetAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AuthSrv_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAdminRequest.ProtoReflect.Descriptor instead.
func (*SetAdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_AuthSrv_proto_rawDescGZIP(), []int{9}
}

func (x *SetAdminRequest) GetTelegramID() int64 {
	if x != nil {
		return x.TelegramID
	}
	return 0
}

type SetAdminResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SetAdminResponse) Reset() {
	*x = SetAdminResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_AuthSrv_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAdminResponse) ProtoMessage() {}

func (x *SetAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AuthSrv_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAdminResponse.ProtoReflect.Descriptor instead.
func (*SetAdminResponse) Descriptor() ([]byte, []int) {
	return file_proto_AuthSrv_proto_rawDescGZIP(), []int{10}
}

func (x *SetAdminResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_AuthSrv_proto protoreflect.FileDescriptor

var file_proto_AuthSrv_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x41, 0x75, 0x74, 0x68, 0x53, 0x72, 0x76, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x41, 0x75, 0x74, 0x68, 0x53, 0x72, 0x76, 0x22, 0x45,
	0x0a, 0x23, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x42, 0x79, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61,
	0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x65, 0x6c, 0x65, 0x67,
	0x72, 0x61, 0x6d, 0x49, 0x44, 0x22, 0x3e, 0x0a, 0x24, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x45, 0x78, 0x69, 0x73, 0x74, 0x42, 0x79, 0x54, 0x65, 0x6c, 0x65, 0x67,
	0x72, 0x61, 0x6d, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0xc6, 0x02, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x49, 0x44,
	0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72,
	0x61, 0x6d, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x6d, 0x61, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x48, 0x61, 0x73, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6d, 0x61,
	0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x48, 0x61, 0x73, 0x68, 0x12, 0x2a,
	0x0a, 0x10, 0x66, 0x61, 0x6b, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x48, 0x61,
	0x73, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x66, 0x61, 0x6b, 0x65, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x48, 0x61, 0x73, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x61, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x6e, 0x22, 0x3e,
	0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x53, 0x72, 0x76, 0x2e,
	0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x22, 0x28,
	0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x62, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x42, 0x79, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6c, 0x65,
	0x67, 0x72, 0x61, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x65,
	0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x48, 0x61, 0x73, 0x68, 0x22, 0x48, 0x0a, 0x1d,
	0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x42, 0x79, 0x54, 0x65, 0x6c, 0x65, 0x67,
	0x72, 0x61, 0x6d, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a,
	0x06, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x53, 0x72, 0x76, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x06,
	0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x22, 0xa8, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4e, 0x65,
	0x61, 0x72, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c,
	0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4c, 0x61, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4c, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x22, 0x3b, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x03, 0x52, 0x0a, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x31,
	0x0a, 0x0f, 0x53, 0x65, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x49,
	0x44, 0x22, 0x24, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0xe2, 0x03, 0x0a, 0x07, 0x41, 0x75, 0x74, 0x68,
	0x53, 0x72, 0x76, 0x12, 0x4d, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x53, 0x72, 0x76, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x53, 0x72, 0x76, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x68, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x42,
	0x79, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x49, 0x44, 0x12, 0x25, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x53, 0x72, 0x76, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x42,
	0x79, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x26, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x53, 0x72, 0x76, 0x2e, 0x47, 0x65, 0x74,
	0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x42, 0x79, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d,
	0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x7d, 0x0a, 0x1c,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x42, 0x79, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x49, 0x44, 0x12, 0x2c, 0x2e, 0x41,
	0x75, 0x74, 0x68, 0x53, 0x72, 0x76, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x45, 0x78, 0x69, 0x73, 0x74, 0x42, 0x79, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61,
	0x6d, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x41, 0x75, 0x74,
	0x68, 0x53, 0x72, 0x76, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x42, 0x79, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x49,
	0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73,
	0x12, 0x21, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x53, 0x72, 0x76, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65,
	0x61, 0x72, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x53, 0x72, 0x76, 0x2e, 0x47, 0x65,
	0x74, 0x4e, 0x65, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x08, 0x53, 0x65, 0x74,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x18, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x53, 0x72, 0x76, 0x2e,
	0x53, 0x65, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x53, 0x72, 0x76, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x41, 0x75, 0x74, 0x68, 0x53, 0x72, 0x76, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_AuthSrv_proto_rawDescOnce sync.Once
	file_proto_AuthSrv_proto_rawDescData = file_proto_AuthSrv_proto_rawDesc
)

func file_proto_AuthSrv_proto_rawDescGZIP() []byte {
	file_proto_AuthSrv_proto_rawDescOnce.Do(func() {
		file_proto_AuthSrv_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_AuthSrv_proto_rawDescData)
	})
	return file_proto_AuthSrv_proto_rawDescData
}

var file_proto_AuthSrv_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_AuthSrv_proto_goTypes = []interface{}{
	(*CheckPersonExistByTelegramIDRequest)(nil),  // 0: AuthSrv.CheckPersonExistByTelegramIDRequest
	(*CheckPersonExistByTelegramIDResponse)(nil), // 1: AuthSrv.CheckPersonExistByTelegramIDResponse
	(*Person)(nil),                        // 2: AuthSrv.Person
	(*CreatePersonRequest)(nil),           // 3: AuthSrv.CreatePersonRequest
	(*CreatePersonResponse)(nil),          // 4: AuthSrv.CreatePersonResponse
	(*GetPersonByTelegramIDRequest)(nil),  // 5: AuthSrv.GetPersonByTelegramIDRequest
	(*GetPersonByTelegramIDResponse)(nil), // 6: AuthSrv.GetPersonByTelegramIDResponse
	(*GetNearValidatorsRequest)(nil),      // 7: AuthSrv.GetNearValidatorsRequest
	(*GetNearValidatorsResponse)(nil),     // 8: AuthSrv.GetNearValidatorsResponse
	(*SetAdminRequest)(nil),               // 9: AuthSrv.SetAdminRequest
	(*SetAdminResponse)(nil),              // 10: AuthSrv.SetAdminResponse
}
var file_proto_AuthSrv_proto_depIdxs = []int32{
	2,  // 0: AuthSrv.CreatePersonRequest.person:type_name -> AuthSrv.Person
	2,  // 1: AuthSrv.GetPersonByTelegramIDResponse.person:type_name -> AuthSrv.Person
	3,  // 2: AuthSrv.AuthSrv.CreatePerson:input_type -> AuthSrv.CreatePersonRequest
	5,  // 3: AuthSrv.AuthSrv.GetPersonByTelegramID:input_type -> AuthSrv.GetPersonByTelegramIDRequest
	0,  // 4: AuthSrv.AuthSrv.CheckPersonExistByTelegramID:input_type -> AuthSrv.CheckPersonExistByTelegramIDRequest
	7,  // 5: AuthSrv.AuthSrv.GetNearValidators:input_type -> AuthSrv.GetNearValidatorsRequest
	9,  // 6: AuthSrv.AuthSrv.SetAdmin:input_type -> AuthSrv.SetAdminRequest
	4,  // 7: AuthSrv.AuthSrv.CreatePerson:output_type -> AuthSrv.CreatePersonResponse
	6,  // 8: AuthSrv.AuthSrv.GetPersonByTelegramID:output_type -> AuthSrv.GetPersonByTelegramIDResponse
	1,  // 9: AuthSrv.AuthSrv.CheckPersonExistByTelegramID:output_type -> AuthSrv.CheckPersonExistByTelegramIDResponse
	8,  // 10: AuthSrv.AuthSrv.GetNearValidators:output_type -> AuthSrv.GetNearValidatorsResponse
	10, // 11: AuthSrv.AuthSrv.SetAdmin:output_type -> AuthSrv.SetAdminResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_AuthSrv_proto_init() }
func file_proto_AuthSrv_proto_init() {
	if File_proto_AuthSrv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_AuthSrv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckPersonExistByTelegramIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_AuthSrv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckPersonExistByTelegramIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_AuthSrv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_AuthSrv_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePersonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_AuthSrv_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePersonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_AuthSrv_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPersonByTelegramIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_AuthSrv_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPersonByTelegramIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_AuthSrv_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNearValidatorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_AuthSrv_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNearValidatorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_AuthSrv_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAdminRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_AuthSrv_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAdminResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_AuthSrv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_AuthSrv_proto_goTypes,
		DependencyIndexes: file_proto_AuthSrv_proto_depIdxs,
		MessageInfos:      file_proto_AuthSrv_proto_msgTypes,
	}.Build()
	File_proto_AuthSrv_proto = out.File
	file_proto_AuthSrv_proto_rawDesc = nil
	file_proto_AuthSrv_proto_goTypes = nil
	file_proto_AuthSrv_proto_depIdxs = nil
}
